### ISSUE TITLE
Everyone is Invited to Help me in Designing Github WorkFlow for this

### ISSUE THREAD

**Issue by Manishmg3994** [tokland/youtube-upload#360]
i was designing a workflow file for this and you can put your code below because i was facing some issues 
```yaml
on:
  pull_request:
    branches:
    # you can add more branches 
      - main
      - master
      - base
      - advanced
      - nobug
      - auth
  push:
    branches:
    # you can add more branches 
      - main
      - master
      - develop
      - base 
      - advanced
      - nobug
      - auth
  workflow_dispatch: # run Workflow Job manually from action tab
name: "Upload Video To Youtube And Create Post in Facebook Page and Create ReadMe.md in Github"
jobs:
  build:
    name: Upload Video To Youtube And Create Post in Facebook Page and Create ReadMe.md in Github
    runs-on: ubuntu-latest
    # runs-on: macos-latest #todo change
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          # cache: 'pip' # caching pip dependencies
      - run: sudo python setup.py install
      # - run: pip install -r requirements.txt
      # - run: python my_script.py
      - run: |
          pwd
           youtube-upload \
            --title="${{ github.event.repository.name }}" \
            # --title="A.S. Mutter" \
            --description="${{ github.event.payload.description }}" \
            # --description="A.S. Mutter plays Beethoven" \ 
            --category="Comedy" \
            --tags="Funny, Comedy , Teen Chapri, 3 Chapri " \ 
            --recording-date="${{ github.event.created_at }}" \ 
            # --recording-date="2011-03-10T15:32:17.0Z" \ 
            --default-language="hi" \
            --default-audio-language="hi" \
            --client-secrets="${{ secrets.GCP }}" \
            --credentials-file="${{ secrets.GCP }}" \
            # --credentials-file="my_credentials.json" \
            # --playlist="My favorite music" \
            # --embeddable=True|False \
            --embeddable=True \
            # --privacy (public | unlisted | private)  
            --privacy= public \
            # --publish-at (YYYY-MM-DDThh:mm:ss.sZ)  
            # --location (latitude=VAL,longitude=VAL[,altitude=VAL])  
            # --thumbnail (string)  
              anne_sophie_mutter.flv
              tx2Zb-145Yz


```
